CREATE ROLE reader WITH LOGIN PASSWORD 'a4xsecret' NOSUPERUSER NOCREATEROLE NOCREATEDB NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE writer WITH LOGIN PASSWORD 'a4xsecret' NOSUPERUSER NOCREATEROLE NOCREATEDB NOINHERIT NOREPLICATION NOBYPASSRLS;
