CREATE ROLE reader WITH LOGIN PASSWORD 'secret' NOSUPERUSER NOCREATEROLE NOCREATEDB NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE writer WITH LOGIN PASSWORD 'secret' NOSUPERUSER NOCREATEROLE NOCREATEDB NOINHERIT NOREPLICATION NOBYPASSRLS;
