CREATE SCHEMA IF NOT EXISTS public;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM reader;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM writer;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO reader;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO writer;